version: "3.9"

services:
  app:
    image: ${MANGAT_IMAGE:-ghcr.io/haruka041/manga-translator:main}
    build:
      context: .
      dockerfile: backend/Dockerfile
    pull_policy: if_not_present
    environment:
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MASTER_KEY: ${MASTER_KEY}
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
